steps:
- id: 'Pull-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:latest']

- id: 'Build-Docker-Image'
  waitFor: ['Pull-docker-image']
  name: 'gcr.io/cloud-builders/docker'
  dir: 'src/flask'
  args: ['build',
         '-t', '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:$SHORT_SHA',
         '-t', '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:latest',
         '--cache-from', '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:latest',
         '-f', 'Dockerfile',
         '.']

- id: 'Push-the-Docker-Image-to-AR'
  waitFor: ['Build-Docker-Image']
  name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:$SHORT_SHA"]

- id: 'Rename-image-hash'
  waitFor: ['Push-the-Docker-Image-to-AR']
  name: 'ubuntu'
  dir: 'k8s-manifests'
  args: [ "sed", "-i", "s^newName: flask^newName: $${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:$SHORT_SHA^g", "kustomization.yaml" ]

- id: 'Update-K8S'
  waitFor: ['Rename-image-hash']
  name: 'gcr.io/cloud-builders/kubectl'
  args: ["apply",'-k', 'k8s-manifests']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_K8S_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_K8S_CLUSTER}'

substitutions:
  _K8S_ZONE: us-east4-c # default value
  _K8S_CLUSTER: demo # default value
  _AR_REGION: us-east4 # default value

images:
- '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/demo/flask:latest'
