apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
        visualize: 'true'
    spec:
      containers:
      - name: flask
        image: flask
        ports:
        - containerPort: 8000
