apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  # annotations:
    # cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: flask
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
#  type: ClusterIP

