apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80