apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flask-deploy.yaml
- flask-svc.yaml
- hpa.yaml

images:
- name: flask
  newName: us-east4-docker.pkg.dev/elatov-demo/demo/flask
